import type { Metadata } from 'next'

import '../../globals.css'

import NavLinks from '../../components/Nav-Links'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
import {
    HiChartPie,
    HiBookOpen,
    HiUsers,
    HiClipboardList,
    HiBell,
    HiCog,
} from 'react-icons/hi'
import ThemeToggle from '@/app/components/ThemeToggle'

const Admin_Links = [
    { name: 'Dashboard', href: '/admin/dashboard', icon: <HiChartPie /> },
    {
        name: 'Book Inventory',
        href: '/admin/dashboard/books',
        icon: <HiBookOpen />,
    },
    { name: 'Member ', href: '/admin/dashboard/users', icon: <HiUsers /> },
    {
        name: 'Loan Tracking',
        href: '/admin/dashboard/loans',
        icon: <HiClipboardList />,
    },
    {
        name: 'Overdue Books',
        href: '/admin/dashboard/overdue',
        icon: <HiBell className="text-red-500 animate-pulse" />, // J'ai ajouté une petite animation de pulsation pour l'alerte
    },
    { name: 'Settings', href: '/admin/dashboard/settings', icon: <HiCog /> },
]
export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <div className="min-h-full flex flex-row  transition-colors duration-300">
            <aside>
                <NavLinks Nav_Links={Admin_Links}></NavLinks>
            </aside>
            {children}
        </div>
    )
}
